### ISSUE TITLE
无法读取挂载的储存服务器中的图片

### ISSUE THREAD

**Issue by williamhyin** [zchrissirhcz/imageset-viewer#7]
您好，

我使用win10端运行您的脚本，想读取我挂载的服务器硬盘中的图片，能显示图片名，但是无法显示图片。
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "imageset-viewer.py", line 353, in callback
    self.tkim = self.get_tkim(im_pth)
  File "imageset-viewer.py", line 379, in get_tkim
    im_ht, im_wt, im_dt = im.shape
AttributeError: 'NoneType' object has no attribute 'shape'

请问您有解决办法吗？
谢谢

**Comment by zchrissirhcz** [comment]
看起来是图片没有被读取出来，具体需要检查：
- 打印出来的图片路径是什么？
- 图片是否存在？
- 图像本身的格式，能否被 get_tkim 所支持？

**Comment by zchrissirhcz** [comment]
Close due to inactiive.
